config/routes.rb
Rails.application.routes.draw do
  
  root 'user#home'

  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy'
  get 'timeout', to: 'session#timeout'

  get 'checkin_frontdesk', to: 'user#checkin_frontdesk'

  get 'checkin_success', to: 'user#checkin_success'

  get 'home', to: 'user#home'

  get 'index', to: 'user#index'#, as: 'login'

  get 'payment', to: 'user#payment'

  get 'personal_form', to: 'user#personal_form'

  get 'update_insurance', to: 'user#update_insurance'

  post 'update_personal', to: 'user#update_personal'
  get 'update_personal', to: 'user#update_personal'

  get 'upload_doc', to: 'user#upload_doc'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :user_timeout

  private

  def current_user
    User.where(id: session[:user_id]).first
  end

  def user_timeout
    if current_user == nil
      redirect_to login_path # unless request.fullpath == '/login'
    else
      if session[:expires_at].nil?
        session[:expires_at] = Time.current + 15.minutes
      elsif session[:expires_at] < Time.current
        redirect_to timeout_path
      else
        session[:expires_at] = Time.current + 15.minutes
      end
    end
  end

  helper_method :current_user
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :user_timeout

  def new
  end

  def create
    # Create a new session by finding the Buyer record that matches the email entered
    user = User.find_by_username(params[:username])
    # If the Buyer record exists and the password entered is correct...
    if user && user.authenticate(params[:password])
      # ...set the session user to that User's ID, set an expiration timer to the session, and redirect to root.
      session[:user_id] = user.id
      session[:expires_at] = Time.current + 15.minutes
      redirect_to '/'
    # ...otherwise, re-render this page.
    else
      render :new
    end
  end

  def destroy
    # Use 'reset session' to completely destroy all session data
    reset_session
    redirect_to '/', notice: 'Logged out!'
  end

  def timeout
    reset_session
    # Use 'reset session' to completely destroy all session data
    redirect_to '/', notice: 'You have been logged out for being inactive too long.'
  end
end

app/controllers/user_controller.rb
require 'ccapi'

class UserController < ApplicationController
  before_action :authorize
  before_action :get_patient, only: [:update_insurance, :update_personal, :payment]
  before_action :confirmation, only: [:checkin_frontdesk, :checkin_success]

  def checkin_frontdesk
  end

  def checkin_success
  end

  def home
    @appointments = []
    api = CareCloudApi.new
    all_appointments = api.appointments
    all_appointments.each do |appointment|
      if appointment["appointment"]["patient"]["id"] == current_user.external_user_id
        @appointments << appointment["appointment"]
      end
    end
    @appointments

  end

  def index
  end

  def payment
    api = CareCloudApi.new
    @copay = api.payment(current_user.external_user_id)#["insurance_profiles"][1]["insurance_policies"].first["co_payment"]
    @balance = api.balance(current_user.external_user_id)[1]["total"]
    # api.
  end

  def personal_form
  end

  def update_insurance
  end

  def update_personal
    session[:appointment] = params[:id]
  end

  def upload_doc
  end

  private

  def authorize
    if current_user.nil?
      redirect_to login_url, alert: "Not authorized! Please log in."
    end
  end

    def get_patient
      api = CareCloudApi.new
      @patient_info = api.patient(current_user.external_user_id)["patient"]
    end

    def confirmation
      api = CareCloudApi.new
      @confirmation = api.confirmation(session[:appointment])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheckinApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<div class="top-bar">
  <%= image_tag("carecloud_logo.png") %>
</div>
<%= form_tag '/login', class:"log-in" do %>
  <h2>Sign In</h2>
    <label> USERNAME: <%= text_field_tag :username %> </label>
<br>
<br>
    <label> PASSWORD: <%= password_field_tag :password %></label>
<br>
<br>

    <%= submit_tag "SIGN IN", id:"submit-button" %>
<%end%>

app/views/user/checkin_frontdesk.html.erb
<div class="checkin">
   <img src="../assets/green_check.png" alt="checkmark"/>
   <br>
   <span>YOU HAVE SUCCESSFULLY CHECKED IN FOR YOUR APPOINTMENT WITH __DOCTOR__ ON __DATE__ AT __TIME__ AT __LOCATION__</span>
 </div>

 <div class="front-desk">
   <span>PLEASE VISIT THE FRONT DESK PRIOR TO YOUR APPOINTMENT</span>
</div>

app/views/user/checkin_success.html.erb
<div class="checkin">
  <img src="../assets/green_check.png" alt="checkmark"/>
  <br>
  <span>YOU HAVE SUCCESSFULLY CHECKED IN FOR YOUR APPOINTMENT WITH __DOCTOR__ ON __DATE__ AT __TIME__ AT __LOCATION__</span>
</div>

app/views/user/confirmation.html.erb
Success

app/views/user/home.html.erb
<div class="top-bar">
  <%= image_tag("carecloud_logo.png") %>
</div>

<div class="appointments white-background">

  <h2 id="upcoming">UPCOMING APPOINTMENTS</h2>
  <% @appointments.each do |app| %>
  <label for="date">Date: </label>
  <%= Date.parse(app["start_time"]).to_s %>
  <br>
  <label for="time">Time: </label>
  <%= Time.parse(app["start_time"]).to_s %>
  <br>
  <label for="doctor">Doctor: </label>
  <%= app["location"]["name"] %>
  <br>
    <div class="appointment-buttons">
      <%= button_to "Confirm", update_personal_path(id: app["id"]) %>
      <% if Date.tomorrow > Date.parse(app["start_time"]) && Date.yesterday < Date.parse(app["start_time"]) && app["appointment_status"]["code"] == "P" %>
        <%= button_to "Check In", checkin_success_path, method: 'get' %>
      <% end %>
    </div>
    <br><br>
  <% end %>

</div>

app/views/user/index.html.erb
<label for='USERNAME'>USERNAME<br>
<input type="text" value="username"><br>
<label for='PASSWORD'>USERNAME<br>
<input type="text" value="password"><br>
<a href="views/home.html"><input type="submit" value="SIGN IN"></a>

app/views/user/payment.html.erb
<!-- <<<<<<< HEAD
<div class="update-personal">
</div>
<div class="payment">
  <span>Pay your Current Balance of $<%#= @balance %></span>
  <br>
  <label for="balance"></label>
  <span>or pay current copay of $25.00<%#= @copay %></span>
  <br>
</div>
<div class="payment-options">
  <a href="checkin_success.html" class="update-personal"><label for="credit-card">Pay Current Balance with Master Card ending in 1234</label></a>
  <br>
  <a href="checkin_success.html" class="update-personal"><label for="credit-card">Pay Copay with Master Card ending in 1234</label></a>
  <br>
  <a href="checkin_frontdesk.html"><input type="button" value="DO NOT PAY"></a>
</div>
======= -->
<body class='payment-body'>
  <div class="payment">
    <span>YOU HAVE A CURRENT BALANCE OF:</span>
    <br>
    <label id='total-balance' for="balance">$<%= @balance %></label>
    <br>
  </div>


  <div class="payment-options">
    <select>
      <option value="card-one">VISA XXXX-XXXX-XXXX-1234</option>
      <option value="card-two">MC XXXX-XXXX-XXXX-1234</option>
    </select>
    <br>
    <a href="checkin_success.html"><input type="button" value="PAY TOTAL"></a>
    <br>
    <a href="checkin_success.html"><input type="button" value="PAY CO-PAY"></a>
    <br>
    <a href="checkin_success.html"><input type="button" value="PAY OTHER AMOUNT"></a>
    <br>
    <a href="checkin_frontdesk.html"><input type="button" value="PAY AT FRONT DESK"></a>
  </div>
</body>
<!-- >>>>>>> c9b39b14a6d8e86f4ba4e15193c36a40b32142b5 -->

app/views/user/personal_form.html.erb
<body class='white-background'>

 <div class="top-bar">
   <img src="../assets/carecloud_logo.png" alt="Care Cloud Logo"/>
 </div>

 <div class="personal-form">

  <h2>PERSONAL INFORMATION</h2>

   <form class="personal-form form" method="post">
     <label for="name">NAME:</label><br>
     <input type="text" placeholder="name"><br>
     <label for="address">ADDRESS:</label><br>
     <input type="text" placeholder="address"><br>
     <label for="city">CITY:</label><br>
     <input type="text" placeholder="city"><br>
     <label for="state">STATE:</label><br>
     <input type="text" placeholder="state"><br>
     <label for="zip-code">ZIP CODE:</label><br>
     <input type="text" placeholder="zip code"><br>
     <label for="country">COUNTRY:</label><br>
     <input type="text" placeholder="country"><br>
     <label for="drivers-license">DRIVERS LICENSE</label><br>
     <input type="text" placeholder="drivers license"><br>
     <label for="primary-phone">PRIMARY PHONE</label><br>
     <input type="text" placeholder="primary phone"><br>
     <label for="secondary-phone">SECONDARY PHONE</label><br>
     <input type="text" placeholder="secondary phone"><br>
     <label for="marital-status">MARITAL STATUS</label><br>
     <input type="text" placeholder="marital status"><br>
   </form>

   <a href="update_insurance.html"><input id='form-button' type="button" value="CONFIRM CHANGES"></a>

 </div>

</body>

app/views/user/update_insurance.html.erb
<div class="update-insurance">
  <span>DO YOU NEED TO UPDATE YOUR INSURANCE INFORMATION?</span>
</div>
<br>
<div class="force-text-yay">
  Insurance Provider: <%= @patient_info["insurance_profiles"][1]["insurance_policies"].first["type"] %><br>
  Member Number: <%= @patient_info["insurance_profiles"][1]["insurance_policies"].first["member_number"] %>
</div>

<div class="update-buttons">
<a href="upload_doc.html"><input type="button" value="YES"></a>
<a href="payment.html"><input type="button" value="NO"></a>
</div>

app/views/user/update_personal.html.erb
<body class='white-background'>
  <div class="top-bar">
     <img src="../assets/carecloud_logo.png" alt="Care Cloud Logo"/>
   </div>

  <div class="update-personal">
    <span>DO YOU NEED TO UPDATE YOUR PERSONAL INFORMATION?</span>
  </div>

  <form class="personal-display" method="post">

    <div class="update-personal">
      <br>
      <label for="name">Patient Name: <%= @patient_info["first_name"].downcase.capitalize %> <%= @patient_info["last_name"].downcase.capitalize %></label><br>
      <label for="address">Street Address: <%= @patient_info["addresses"][0]["line1"] %></label><br>
      <label for="city">City: <%= @patient_info["addresses"][0]["city"].downcase.capitalize %></label><br>
      <label for="state">State: <%= @patient_info["addresses"][0]["state"] %></label><br>
      <label for="zip-code">Zip Code: <%= @patient_info["addresses"][0]["zip"] %></label><br>
      <label for="primary-phone">Phone Number: <%= @patient_info["phones"][0]["phone_number"] %></label>
      <!-- <label for="drivers-license">#########</label><br>
      <label for="drivers-license-state">FL</label><br>
      <label for="marital-status">Married</label><br> -->
    </div>

  </form>

  <div class="update-buttons">
    <a href="personal_form.html"><input id='update-yes' type="button" value="YES"></a>
    <br>
    <a href="update_insurance.html"><input id='update-no' type="button" value="NO"></a> 
  </div>
</body>

app/views/user/upload_doc.html.erb
<body class='white-background'>

 <div class="top-bar">
   <img src="../assets/carecloud_logo.png" alt="Care Cloud Logo"/>
 </div>

 <h2 id="uploadh2">UPLOAD DOCUMENTS</h2>

 <p>IF YOU MADE CHANGES TO YOUR PERSONAL INFORMATION OR NEED TO UPDATE YOUR INSURANCE INFORMATION UPLOAD YOUR ID AND INSURANCE CARD</p>

 <div class="upload-documents">
   <br>
   <a href="#"><input type='button' value='PHOTO ID'></a>
   <br>
   <a href="#"><input type='button' value='INSURANCE CARD'></a>
   <br>
 </div>

 <a href="payment.html"><input id='confirm-button' type="button" value="CONFIRM CHANGES"></a>

</body>